server:
  port: ${SERVER_PORT:4550}

spring:
  application:
    name: service-cp-crime-hearing-case-event-subscription
  jpa:
    open-in-view: false
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/appdb}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

material-client:
  url: ${MATERIAL_CLIENT_URL:http://localhost:8081}
  cjscppuid: ${CJSCPPUID:00000000-0000-0000-0000-000000000000}
  retry:
    intervalMilliSecs: ${MATERIAL_CLIENT_INTERVAL_MSECS:500}
    timeoutMilliSecs: ${MATERIAL_CLIENT_TIMEOUT_MSECS:60000}

callback-client:
  retry:
    intervalMilliSecs: ${CALLBACK_CLIENT_INTERVAL_MSECS:200}
    timeoutMilliSecs: ${CALLBACK_CLIENT_TIMEOUT_MSECS:5000}

service-bus:
  enabled: ${SERVICE_BUS_ENABLED:false}
  admin-connection: ${SERVICE_BUS_ADMIN_CONNECTION:Endpoint=sb://localhost:5300;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;}
  connection: ${SERVICE_BUS_CONNECTION:Endpoint=sb://localhost;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=SAS_KEY_VALUE;UseDevelopmentEmulator=true;}
  retry-msecs: ${SERVICE_BUS_RETRY_SECONDS:0,1000,2000,10000,60000,600000}
  max-tries: ${SERVICE_BUS_MAX_TRIES:10}

document-service:
  url: ${DOCUMENT_SERVICE_URL:http://localhost:8082}

subscription:
  oauth-enabled: ${SUBSCRIPTION_OAUTH_ENABLED:true}

hmac:
  vault-enabled: ${HMAC_VAULT_ENABLED:false}

vault:
  uri: ${AZURE_VAULT_URI:}


management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health, info, prometheus
